### ISSUE TITLE
I got this error messge when I tried

### ISSUE THREAD

**Issue by orsenthil** [schacon/showoff-wrangling-git#1]
:public is no longer used to avoid overloading Module#public, use :public_folder instead
        from /Users/skumaran/.gem/gems/showoff-0.7.0/bin/../lib/showoff.rb:39
You should include GLI::App instead
GLI.run no longer works for GLI-2, you must just call `run(ARGV)' instead
either fix your app, or use the latest GLI in the 1.x family

Something wrong? ( I am giving up for the moment as I was curious about showoff and wanted see).

**Comment by lsmith77** [comment]
same here

**Comment by mufid** [comment]
Same here, got the same problem.

**Comment by remyleone** [comment]
I got the same problem using ubuntu 12.10

**Comment by jrhorn424** [comment]
This is a problem with the showoff gem and should probably be reported on that issue tracker.

**Comment by orsenthil** [comment]
I got over it by gem uninstall showoff and gem install showoff --version '0.0.5'
