### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by utdrmac** [schacon/showoff-wrangling-git#2]
asura:showoff-wrangling-git drmac$ showoff serve
error: no implicit conversion of String into Integer

Not sure what this means. Just trying showoff for first time. Not familiar with Ruby at all.

**Comment by meekrosoft** [comment]
Would love an answer to this...

**Comment by lidonghua** [comment]
It seems the configuration file `showoff.json` of this project isn't compatible with the latest versions of showoff.

Modify it as the following:

``` json
{
  "sections": [
    {"section":"title"},
    {"section":"about_me"},
    {"section":"git_in_60"},
    {"section":"debugging"},
    {"section":"environment"},
    {"section":"describe"},
    {"section":"bundles"},
    {"section":"branch_manage"},
    {"section":"tracking"},
    {"section":"new_stuff"},
    {"section":"replace"},
    {"section":"rerere"},
    {"section":"cherry"},
    {"section":"customizing_git"},
    {"section":"hub"},
    {"section":"final"}
  ]
}
```
